version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://server:5000/api
    depends_on:
      - server